# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0002_izin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='izin',
            old_name='disetuji',
            new_name='disetujui',
        ),
    ]
